# Generated by Django 5.1.7 on 2025-04-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('course_core_technologies', models.CharField(blank=True, max_length=255, null=True)),
                ('course_level', models.CharField(blank=True, max_length=50, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('about_couse', models.TextField(blank=True, null=True)),
                ('what_you_will_learn', models.TextField(blank=True, null=True)),
                ('contributors', models.TextField(blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('course_upload_date', models.DateTimeField(auto_now_add=True)),
                ('course_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
