# Generated by Django 5.1.7 on 2025-04-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_description', models.TextField(blank=True, null=True)),
                ('chapter_upload_date', models.DateTimeField(auto_now_add=True)),
                ('chapter_update_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField(blank=True, null=True)),
                ('advantages', models.TextField(blank=True, null=True)),
                ('disadvantages', models.TextField(blank=True, null=True)),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='example_images/')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_detail', to='myapp.chapter')),
            ],
        ),
    ]
