# Generated by Django 5.1.7 on 2025-04-08 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chapter_chapterdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about_couse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='what_you_will_learn',
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_description', models.TextField(blank=True, null=True)),
                ('about_couse', models.TextField(blank=True, null=True)),
                ('what_you_will_learn', models.TextField(blank=True, null=True)),
                ('contributors', models.TextField(blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_detail', to='myapp.course')),
            ],
        ),
    ]
