# Generated by Django 5.1.7 on 2025-04-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_course_about_couse_remove_course_contributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterdetail',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
