# Generated by Django 5.1.7 on 2025-04-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chapterdetail_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_description',
        ),
    ]
