# Generated by Django 5.1.7 on 2025-04-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_chapter_chapter_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterdetail',
            old_name='advantages',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='chapterdetail',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='chapterdetail',
            name='disadvantages',
        ),
        migrations.RemoveField(
            model_name='chapterdetail',
            name='features',
        ),
    ]
